before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

dockers:
  - image_templates:
    - "ghcr.io/sebasptsch/traefik-cloudflare-tunnel:{{ .Version }}-amd64"
    - "ghcr.io/sebasptsch/traefik-cloudflare-tunnel:latest-amd64"
    - "ghcr.io/sebasptsch/traefik-cloudflare-tunnel:latest"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
    - "--platform=linux/amd64"
    
  - image_templates:
    - "ghcr.io/sebasptsch/traefik-cloudflare-tunnel:{{ .Version }}-arm64v8"
    - "ghcr.io/sebasptsch/traefik-cloudflare-tunnel:latest-arm64v8"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
    - "--platform=linux/arm64/v8"
  
docker_manifests:
  - name_template: "sebasptsch/traefik-cloudflare-tunnel:{{ .Version }}"
    image_templates:
    - "ghcr.io/sebasptsch/traefik-cloudflare-tunnel:{{ .Version }}-amd64"
    - "ghcr.io/sebasptsch/traefik-cloudflare-tunnel:{{ .Version }}-arm64v8"
